### ISSUE TITLE
Feature request: exclude other URL-schemes

### ISSUE THREAD

**Issue by guidoboller** [pengx17/logseq-plugin-link-preview#110]
An option to exclude URL schemes other than https:// would be very helpful

**Comment by pengx17** [comment]
Sorry, I don't understand what it means by hiding the scheme. Can you elaborate more?

**Comment by guidoboller** [comment]
I have application specific URL-schemes (e.g. linking to DevonThink-File:  x-devonthink-item://97A82E9D-F871-44A3-983C-F2AECF8352EA) which I use in Logseq as I use http://-based links. Since no preview is available for these application-specific links, I would like to exclude them from the preview function as they only produce "Failed to load link metadata" errors.

**Comment by guidoboller** [comment]
Thanks for fixing it!
