### ISSUE TITLE
link-preview.ts(37,37): error Object is of type 'unknown' 

### ISSUE THREAD

**Issue by Bad3r** [pengx17/logseq-plugin-link-preview#48]
Hi, 

I am trying to deploy the plugin on vercel.

I forked your repo and followed the steps in the readme.

- fork this plugin repository  
- import your forked repository as a new project in Vercel  
- configure it with `FRAMEWORK PRESET` to Other  
- override `INSTALL COMMAND` in Build settings to `npm i pnpm -g && pnpm i`  
- click deploy. After deploy is done, you can now replace the `https://logseq-plugin-link-preview.vercel.app` with your own backend URL.  
 

![](https://user-images.githubusercontent.com/25513724/143901077-2501c3d6-e403-47dd-8f38-32c3c55d75b5.png)

While deploying I received the error

![](https://user-images.githubusercontent.com/25513724/143901272-4eb3484d-34a6-466e-894f-7f1367b9a750.png)

Initially I thought it was due to the output directory `dist`. I tried to force the creation of the directory by modifying the build command --> `mkdir -p && npm i pnpm -g && pnpm i`.   
The output directory error went away, but the second error still exists

![](https://user-images.githubusercontent.com/25513724/143902152-1a09e5db-11f5-4c38-bd79-c02a7306d9b2.png)

I added the full error log in \[this gist\](https://gist.github.com/Bad3r/7c5ffa0e21d0eea4f59a3b479138c849).

**Comment by Bad3r** [comment]
Also are you sure that for \`FRAMEWORK PRESET\` it should be set to `other`? 

In `package.json`   
\`\`\`JSON  
  "scripts": {  
   "dev": "vite",  
   "build": "vite build",  
   "dev:api": "vercel dev --listen 3001"  
 },  
\`\`\`

Shouldn't the framework be `vite`?

Because `package.json` build command is, `build": "vite build"` wouldn't this be replaced with the custom command `npm i pnpm -g && pnpm i` during the build process?

**Comment by pengx17** [comment]
Hi @Bad3r , sorry I made a mistake in the readme. You should put the build settings in `INSTALL COMMAND`:

![image](https://user-images.githubusercontent.com/584378/143966365-3cf79c9c-4459-4d4f-bb62-985aa6f8b7b9.png)

**Comment by Bad3r** [comment]
Thank you! That made the build pass. FYI the error still shows up but the build successes   
 

![](https://user-images.githubusercontent.com/25513724/143970333-5715be49-3b22-4a58-845d-8ce5d5615a9c.png)

**Comment by pengx17** [comment]
@Bad3r hmm, I have seen the same error log in my deployment build. Can you check if your service is working or not?

**Comment by pengx17** [comment]
@Bad3r I pushed a new change. Can you merge your fork with my latest change and try again?

**Comment by Bad3r** [comment]
Thank you! That fixed it!  
It deployed successfully after merging, and I tested it, and it works as expected
