### ISSUE TITLE
Failed to load link metadata.

### ISSUE THREAD

**Issue by xiaoheiAh** [pengx17/logseq-plugin-link-preview#67]
Couldn't fetch preview from any url. Were there some configuration should be setting? I tried to set proxy mode, but not work.

Plugin version: v2.0.0
Logseq version: v0.6.5

<img width="600" alt="image" src="https://user-images.githubusercontent.com/27981726/160338965-f2be8dc3-7bf4-4ee1-82f3-e6bf52780db3.png">

**Comment by pengx17** [comment]
@xiaoheiAh Can you please open the dev tools and see if there is any failed network requests?

**Comment by xiaoheiAh** [comment]
```curl
curl 'https://logseq-plugin-link-preview.vercel.app/api/link-preview?url=https%3A%2F%2Fgithub.com%2Fjbranchaud%2Ftil' \
  -H 'authority: logseq-plugin-link-preview.vercel.app' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Logseq/0.6.5 Chrome/94.0.4606.71 Electron/15.1.2 Safari/537.36' \
  -H 'accept: */*' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'accept-language: zh-CN' \
  --compressed
```

<img width="881" alt="image" src="https://user-images.githubusercontent.com/27981726/160365013-4d3209ae-6c2d-411c-b947-5680b875ad80.png">

**Comment by pengx17** [comment]
Oh, please try to upgrade the plugin to 2.1.0. The old remote server is being taken down and sending requests without using a cors proxy.
