### ISSUE TITLE
Display is wrong when there are multiple link cards

### ISSUE THREAD

**Issue by usoonees** [pengx17/logseq-plugin-link-preview#92]
![May-07-2022 00-16-48](https://user-images.githubusercontent.com/56818734/167172372-6b4be7a5-c440-432b-a963-68c76b7ce7ae.gif)

**Comment by pengx17** [comment]
Thanks for pointing this out. It reminds me a similar issue I fixed a couple of days ago in https://github.com/pengx17/logseq-plugin-todo-master/issues/20#issuecomment-1115280718
